name: CI

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
  pull_request:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version if needed

      - name: Build with Maven
        run: mvn -B clean package  # Assuming you're using Maven as your build tool

      - name: Run JUnit Tests
        run: mvn -B test  # Adjust this command based on your testing setup

      - name: Generate Test Report
        if: always()  # Always generate the test report, even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/surefire-reports  # Adjust the path to your test report directory
