name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'  # or 'adopt', 'zulu', or 'openjdk'

    - name: Compile and run tests
      run: |
        javac Calculator.java TestCalculateOutput.java
        java TestCalculateOutput

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml
