name: CI 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # Or specify the distribution type you prefer, such as 'adopt' or 'temurin'

    - name: Build with Gradle
      run: ./gradlew build --distribution-type=wrapper

    - name: Run unit tests
      run: ./gradlew test --distribution-type=wrapper

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results
